version: '3.9'

services:
  RTProAI:
    build: ./
    container_name: RTProAI-c
    ports:
      -"8000":8000
    volumes:
      -.:/home/app
    networks:
      - network
    depends_on:
      - LLM
    
  LLM:
    image: ollama/ollama:0.11.5-rc4-rocm
    networks:
      - network


networks:
  network:
    driver: bridge